import { Post } from './types';

export const INITIAL_POSTS: Post[] = [
  {
    id: '1',
    title: 'Figma Design System 2026',
    description: 'Our updated core design token system, UI components library, and dark/light typography scales for web projects.',
    url: 'https://figma.com',
    type: 'resource',
    user_id: 'usr-1',
    user_name: 'Sarah Chen (Lead Designer)',
    user_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    avg_rating: 4.9,
    ratings_count: 14,
    views_count: 142,
    clicks_count: 88,
    tags: ['Design', 'Figma', 'UI/UX', 'Tokens'],
    image_url: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&auto=format&fit=crop&q=80',
    featured: true,
  },
  {
    id: '2',
    title: 'Retro Arcade - Cyber Runner 2049',
    description: 'Fast-paced 2D canvas synthwave endless runner game with procedural obstacles, powerups, and global highscores.',
    url: 'https://playcanv.as',
    type: 'game',
    user_id: 'usr-2',
    user_name: 'Alex Rivera (Game Dev)',
    user_avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
    avg_rating: 4.8,
    ratings_count: 29,
    views_count: 320,
    clicks_count: 215,
    tags: ['Game', 'Arcade', 'Canvas', 'WebGL'],
    image_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
    featured: true,
  },
  {
    id: '3',
    title: 'API Gateway & Microservices Hub',
    description: 'Centralized developer portal for testing internal REST APIs, viewing OpenAPI specifications, and generating auth tokens.',
    url: 'https://github.com',
    type: 'project',
    user_id: 'usr-3',
    user_name: 'Marcus Vance (Backend Lead)',
    user_avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    created_at: new Date(Date.now() - 3600000 * 48).toISOString(),
    avg_rating: 4.7,
    ratings_count: 9,
    views_count: 98,
    clicks_count: 45,
    tags: ['Backend', 'API', 'Docker', 'Swagger'],
    image_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
    featured: false,
  },
  {
    id: '4',
    title: 'Vite 6 Optimization Checklist',
    description: 'Internal guide and benchmarking script to cut bundle sizes by 40% using code splitting and modern ES module targets.',
    url: 'https://vite.dev',
    type: 'resource',
    user_id: 'usr-4',
    user_name: 'Elena Rostova (Frontend)',
    user_avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    created_at: new Date(Date.now() - 3600000 * 72).toISOString(),
    avg_rating: 4.9,
    ratings_count: 22,
    views_count: 280,
    clicks_count: 190,
    tags: ['Frontend', 'Vite', 'Performance', 'React'],
    image_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    featured: false,
  },
  {
    id: '5',
    title: 'Space Odyssey 3D Simulator',
    description: 'Interactive solar system exploration with realistic orbital physics, satellite tracking, and high-res planetary textures.',
    url: 'https://threejs.org',
    type: 'game',
    user_id: 'usr-2',
    user_name: 'Alex Rivera (Game Dev)',
    user_avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    created_at: new Date(Date.now() - 3600000 * 96).toISOString(),
    avg_rating: 4.6,
    ratings_count: 18,
    views_count: 210,
    clicks_count: 130,
    tags: ['ThreeJS', '3D', 'Simulation', 'Physics'],
    image_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    featured: false,
  },
];
